Repository yourssu-rookies/unscramble-android-2, pull requests merged in 2024-01, with the labels that each got.

#3 [feat#2] 기초 setting
  .idea/.name
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/androidTest/java/com/urssu/unscramble/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ursssu/unscramble/MyApplication.kt
  app/src/main/java/com/ursssu/unscramble/data/datasource/SharedPreference.kt
  app/src/main/java/com/ursssu/unscramble/data/repository/MockRepository.kt
  app/src/main/java/com/ursssu/unscramble/domain/model/MockModel.kt
  app/src/main/java/com/ursssu/unscramble/domain/repository/MockRepository.kt
  app/src/main/java/com/ursssu/unscramble/presentation/MainActivity.kt
  app/src/main/java/com/ursssu/unscramble/util/extension/ContextExt.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/navigation/navigation.xml
  build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  settings.gradle.kts
Labels: chore

#4 [docs#1] add Readme
  README.md
Labels: docs

#8 [feat#6] Navigation 구현
  app/build.gradle.kts
  app/src/main/java/com/ursssu/unscramble/presentation/EndFragment.kt
  app/src/main/java/com/ursssu/unscramble/presentation/GameStartFragment.kt
  app/src/main/java/com/ursssu/unscramble/presentation/HomeFragment.kt
  app/src/main/java/com/ursssu/unscramble/presentation/MainActivity.kt
  app/src/main/java/com/ursssu/unscramble/presentation/TimerFragment.kt
  app/src/main/java/com/ursssu/unscramble/util/binding/BaseFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_end.xml
  app/src/main/res/layout/fragment_game_start.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_timer.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/navigation/navigation.xml
Labels: feat

#13 [init#12] : .gitignore 파일 업데이트
  .gitignore
Labels: init

#14 [init] YDS에 없는 색 추가
  app/src/main/res/values/colors.xml
Labels: init
